### ISSUE TITLE
Disable "smartness" of the compiler

### ISSUE THREAD

**Issue by matthiasfeist** [globalizejs/globalize-compiler#10]
If I have the following code in my project:

```
    var curr = 'USD';
    var currentcyFormatter = Globalize.currencyFormatter( curr );
    var cur = currentcyFormatter(123.123123);
```

I get the following error message `curr is not defined` 
I think the compiler is trying to be a little bit too smart here and is trying to figure out which cldr data to include. But when I load stuff like this e.g. from a API, it can't know this just from the code.

So is there a option to disable this and to just tell the compiler maybe statically which data to include instead of trying to deduce it from the source?

**Comment by rxaviers** [comment]
Actually, the goal of the compiler is to create runtime code for you. That means: fast and small code that doesn't require CLDR.

The compiler could be a little smarter and figure out that the `curr` variable is actually a constant and has a static value of `"USD"` and use that. But, note a variable could be "variable" (not a constant as in your example) and the solution could be undetermined at the compiler level/time. For example:

```
    var curr = fn(x, y, z);
    var currentcyFormatter = Globalize.currencyFormatter( curr );
```

Should we include all the code and data for all the available currencies? Including the whole code and data to allow any currency basically leads us back to step 0, where we are actually using Globalize normal modules, not the runtime modules. Note, this only gets worse if more and more variables are undetermined, for example:

```
    var currentcyFormatter = Globalize.currencyFormatter( currencyFn(x, y, z), optionsFn(a, b, c) );
```

Here we would have to include all the code and data for all the available currency formatters. For that reason, I suggest a different approach in your code:

``` js
var currentcyFormatter = Globalize.currencyFormatter( curr );
```

If you need multiple formatters, do this:

```
var currentcyFormatter = {
  USD: Globalize.currencyFormatter('USD'),
  EUR: Globalize.currencyFormatter('EUR'),
  ...
}

currentcyFormatter.USD(123.123123);
```

**Comment by rxaviers** [comment]
I have closed this issue, but feel free to post new comments if you have any other question or suggestion. Thanks

**Comment by matthiasfeist** [comment]
Thanks for the answer :)

**Comment by rxaviers** [comment]
I'm reopening this issue so that we can brainstorm about potential ways to solve this. One is to allow the compiler to take an option with a list of supported currencies and use that list of currencies instead of the static currency (or probably a variable) it finds in the code.
