### ISSUE TITLE
Multiple locales

### ISSUE THREAD

**Issue by quentindemetz** [globalizejs/globalize-compiler#3]
Hello @rxaviers,

What's your tip to create a compiled globalize version which includes multiple locales ?

**Comment by rxaviers** [comment]
If you are using the API, simply pass all formatters in all the locales you want support. For example:

``` js
var locales = ["ar", "de", "es", "en", "pt", "ru", "zh"];
.compile(locales.map(function(locale) {
  return Globalize(locale).numberFormatter();
}));
```

If you are using the CLI, you may need to compile individually for each locale then concat the final bundles.

```
for L in ar de es en pt ru zh; do
  globalize-compiler -l $L -o bundle-$L.js SRC_FILES
done
cat bundle* > bundle-all.js
```

I am open for feedback on how this could be improved.

**Comment by quentindemetz** [comment]
Thanks for your feedback, this looks like a good start, I'll let you know if I have some improvements to suggest.

**Comment by rxaviers** [comment]
Excellent


## 

+55 (16) 98138-1583, +1 (415) 568-5854, skype: rxaviers
http://rafael.xavier.blog.br

**Comment by quentindemetz** [comment]
I'm trying to implement this; and struggling to get started:

``` javascript
var Globalize = require('globalize');
Globalize.load.apply(Globalize, require('src/i18n/cldrFiles'));
var globalizeCompiler = require('globalize-compiler');
var bundle = globalizeCompiler.compile([Globalize('en').numberFormatter()]);
>>> Error: No formatters or parsers has been provided
```

Thanks

**Comment by rxaviers** [comment]
Please, make sure you have Globalize 1.1.x-rc (note stable Globalize@1.1.x should be released soon).

```
npm install globalize@1.1.0-rc.7 globalize-compiler cldr-data
```

``` js
var Globalize = require('globalize');
var globalizeCompiler = require('globalize-compiler');
var cldrData = require('cldr-data');
var supportedLocales = ['ar', 'de', 'es', 'en', 'pt', 'ru', 'zh'];
Globalize.load(cldrData.entireSupplemental());
Globalize.load(cldrData.entireMainFor.apply(null, supportedLocales));
globalizeCompiler.compile(supportedLocales.map(function(locale) {
    return Globalize(locale).numberFormatter();
}));
```
