### ISSUE TITLE
Parse function in globalize-compiler production example is not working

### ISSUE THREAD

**Issue by aborja79** [globalizejs/globalize-compiler#38]
I'm trying to use globalize parser but I get an error in production, in development example is working.

`Globalize.dateParser({`` date: "medium" })( "Nov 1, 2010" );`
Uncaught TypeError: Globalize.dateParser(...) is not a function
  
`Globalize.parseNumber("1000.10");`
Uncaught TypeError: this.numberParser(...) is not a function

**Comment by rxaviers** [comment]
Please, provide a simplified example on how to reproduce the issue you describe including the modules versions you're using. Will reopen after that info. Thanks

**Comment by aborja79** [comment]
In production.html file in last script section append
`
    <script>
        Globalize.locale("en");
        Globalize.dateParser({ date: "medium" })("Nov 1, 2010");
    </script>
`
Yo will get the error

**Comment by rxaviers** [comment]
Which production.html?

**Comment by aborja79** [comment]
https://github.com/globalizejs/globalize/blob/master/examples/globalize-compiler/production.html

**Comment by rxaviers** [comment]
You need to add that in [app.js](https://github.com/globalizejs/globalize/blob/master/examples/globalize-compiler/app.js), so it takes that parser into account when compiling.

**Comment by aborja79** [comment]
Ok. Yes if I append in app.js is working. 
Could I get a full methods compiled file or must I call to all methods one to one in app.js?
Thank you
