### ISSUE TITLE
What if I use Babel and wrappers around Globalize module?

### ISSUE THREAD

**Issue by SleepWalker** [globalizejs/globalize-compiler#4]
Hello,

I use the following function to get translations:

``` [js]
import Globalize from 'globalize';
export function t(category, key, ...params) {
    return Globalize.formatMessage(category + '/' + key, ...params);
}
```

Here I have the following issues:
- I can't use `import`, because babel renames variables
- I can't use spread operator, because the function will be expanded to e.g. `Globalize.formatMessage.apply(Globalize, [category + '/' + key].concat(Array.from(arguments)))`
- and finally I can't use wrapper because ast won't be used to parse for different calls

Is there any workaround or it is impossible to get compiler working?

**Comment by rxaviers** [comment]
Your approach is non-deterministic for the compiler, more details can be found in this analogous question https://github.com/jquery-support/globalize-compiler/issues/10#issuecomment-173571256.

Having said that, one approach is writing your own compiler that would look for the `t` function in your code and call globalize-compiler with appropriate code. [rxaviers/react-globalize-webpack-plugin](https://github.com/rxaviers/react-globalize-webpack-plugin) could be used as baseline.

I'm closing your issue given the above reply, but feel free to include additional comments if you have any further questions.
