### ISSUE TITLE
Customize template

### ISSUE THREAD

**Issue by nkovacs** [globalizejs/globalize-compiler#6]
Instead of having to hack the output of the compiler like [this](https://github.com/rxaviers/globalize-webpack-plugin/blob/master/GlobalizeCompilerHelper.js#L78) or using the SkipAMDPlugin, you could just add an option to the compiler:

```
globalizeCompiler.compile(formattersAndParsers, {
    template: fs.readFileSync( __dirname + "/my_globalize.template" ).toString( "utf-8" );
});
```

**Comment by rxaviers** [comment]
Sounds great! I'd be happy to merge this change. Could you submit a PR please? Thanks

**Comment by nkovacs** [comment]
Ok, I'll give it a shot.
One question: is there a reason for separating `{{dependenciesVars}}` and `{{compiled}}` in the template? I'd like to merge them before passing them to the template, to keep things simple.
